name: tfm
channels:
  - bokeh
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - aom=3.5.0
  - asttokens=2.0.5
  - async_generator=1.10
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.4
  - bokeh=3.1.1
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-blosc2=2.9.2
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - cartopy=0.21.1
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charls=2.4.2
  - charset-normalizer=2.0.4
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - cmdstan=2.31.0
  - cmdstanpy=1.1.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - cryptography=38.0.4
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - curl=8.1.2
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - datashader=0.15.0
  - datashape=0.5.4
  - dav1d=1.2.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.1
  - executing=0.8.3
  - expat=2.5.0
  - firefox=114.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.4.0
  - geckodriver=0.33.0
  - geojson=3.0.1
  - geopandas-base=0.13.0
  - geos=3.11.2
  - geotiff=1.7.1
  - geoviews=1.10.0
  - geoviews-core=1.10.0
  - gettext=0.21.1
  - giflib=5.2.1
  - h11=0.14.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - holoviews=1.16.0
  - hvplot=0.8.3
  - icc_rt=2022.1.0
  - icu=72.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.28.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.15.0
  - ipython=8.12.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jsonschema=4.17.3
  - jupyter_bokeh=3.0.7
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - kealib=1.5.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.2
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.0
  - libglib=2.76.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libpng=1.6.39
  - libpq=15.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvmlite=0.40.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - m2-bash=4.3.042
  - m2-coreutils=8.25
  - m2-filesystem=2016.04
  - m2-gcc-libs=5.3.0
  - m2-gmp=6.1.0
  - m2-libiconv=1.14
  - m2-libintl=0.19.7
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-sed=4.2.2
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.4.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbformat=5.7.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.3
  - networkx=3.1
  - numba=0.57.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.0
  - openpyxl=3.0.10
  - openssl=3.1.1
  - outcome=1.2.0
  - packaging=23.0
  - pandas=1.5.2
  - panel=1.0.3
  - param=1.13.0
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pip=23.0.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pooch=1.7.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.5.0
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyrsistent=0.18.0
  - pysheds=0.3.5
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytz=2022.7
  - pyviz_comms=2.3.0
  - pywavelets=1.4.1
  - pywin32=305
  - pyyaml=6.0
  - pyzmq=25.0.2
  - rasterio=1.3.7
  - requests=2.29.0
  - rioxarray=0.14.1
  - scikit-image=0.18.1
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - selenium=4.10.0
  - setuptools=67.8.0
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tiledb=2.13.2
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - traitlets=5.7.1
  - trio=0.22.0
  - trio-websocket=0.10.3
  - typing_extensions=4.5.0
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ucrt=10.0.22621.0
  - urllib3=1.26.15
  - vc=14.2
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - wsproto=1.2.0
  - xarray=2022.11.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - asciitree==0.3.3
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - cachetools==5.3.1
      - cfgrib==0.9.10.4
      - contourpy==1.0.7
      - convertdate==2.4.0
      - distributed==2022.7.0
      - docopt==0.6.2
      - eccodes==1.5.2
      - entrypoints==0.4
      - ephem==4.1.4
      - fasteners==0.18
      - findlibs==0.0.5
      - flatbuffers==23.5.26
      - flox==0.7.2
      - fonttools==4.38.0
      - gast==0.4.0
      - google-auth==2.20.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5netcdf==1.1.0
      - h5py==3.8.0
      - hijri-converter==2.2.4
      - holidays==0.19
      - importlib-resources==5.12.0
      - kaleido==0.1.0.post1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - keras-tuner==1.3.5
      - korean-lunar-calendar==0.3.1
      - kt-legacy==1.0.5
      - libclang==16.0.0
      - lunarcalendar==0.0.9
      - matplotlib==3.7.0
      - msgpack==1.0.5
      - nc-time-axis==1.4.1
      - numbagg==0.2.2
      - numcodecs==0.11.0
      - numpy-groupies==0.9.22
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pillow==9.4.0
      - prophet==1.1.2
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydap==3.4.1
      - pymeeus==0.5.12
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - seaborn==0.12.2
      - soupsieve==2.4.1
      - tblib==1.7.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tornado==6.1
      - webob==1.8.7
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - zarr==2.14.2
      - zict==3.0.0