import os
from pathlib import Path

PACKAGE_DIR = os.path.dirname(os.path.dirname(__file__))
DATA_DIR = Path(os.path.join(PACKAGE_DIR, 'data'))
OBSERVACIONS_DIR = Path(os.path.join(DATA_DIR, 'observacions'))
OBSERVACIONS_FILTRAT_DIR = Path(os.path.join(DATA_DIR, 'observacions_filtrat'))
ESTACIONS_DIR = Path(os.path.join(DATA_DIR, 'estacions_cabal.csv'))
TRAIN_TEST_INDEX_DIR = Path(os.path.join(DATA_DIR, 'splits_train_test'))
TRAIN_TEST_SERIES_DIR = Path(os.path.join(DATA_DIR, 'splits_train_test_series'))
OPTIMIZATION_DIR = Path(os.path.join(DATA_DIR, 'optimization'))
DATA_MODEL_DIR = Path(os.path.join(DATA_DIR, 'model'))
SWAT_PREDICTIONS_DIR = Path(os.path.join(DATA_DIR, 'predictions'))
LSTM_DATA_DIR = Path(os.path.join(DATA_DIR, 'lstm_data'))
LSTM_MODELS_DIR = Path(os.path.join(DATA_DIR, 'lstm_models'))
LSTM_HYPEROPT_DIR = Path(os.path.join(DATA_DIR, 'lstm_hyperopt'))
LSTM_CALIBRATED_DIR = Path(os.path.join(DATA_DIR, 'lstm_calibrated'))
LSTM_PREDICTIONS_DIR = Path(os.path.join(DATA_DIR, 'lstm_predictions'))
UNGAUGED_DIR = Path(os.path.join(DATA_DIR, 'ungauged'))
AUTOENCODER_DIR = Path(os.path.join(DATA_DIR, 'autoencoder'))